version: '3.8'

services:
  fastapi-app:
    build:
      context: . # The directory containing your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # Map host port 8001 to container port 8001
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]
