name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies (optional for deploy)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # If you still want to run final tests before deploying:
          pip install pytest coverage

      - name: (Optional) Final Test Check
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # or password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /path/to/your/app
            git pull
            docker-compose down
            docker-compose up -d
