name: Python CI

on:
  push:
    branches: [ pre ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # or your preferred version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Example lint/test tools:
          pip install flake8 pytest coverage

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report -m
